# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'gcp-base'

    ## define basic info
    config.vm.define 'chousei_api_wrapper_local' do |d|
        d.vm.hostname = 'chousei-api-wrapper-local'
        d.vm.network 'private_network', ip: '192.168.50.13'
    end

    ## define spec
    config.vm.provider 'virtualbox' do |p|
        p.memory = 2048
    end

    ### for application
    config.vm.synced_folder '../', '/home/vagrant/repos', owner: 'vagrant', group: 'vagrant', create: true
end

